binary_sensor:
  # TEST für binary_sensor
  - name: "Vitocal Kompressor Status TEST"
    state_topic: "open3e/680_2351_HeatPumpCompressor"
    unique_id: 680_2351_HeatPumpCompressor_TEST
    payload_off: "0.0"
    payload_on: "1.0"
    device_class: running
    icon: mdi:toggle-switch-variant

sensor:
  # Vitocal 250 - Allgemein
  - name: "Vitocal Vorlauftemperatur"
    state_topic: "open3e/680_268_FlowTemperatureSensor/Actual"
    unique_id: 680_268_FlowTemperatureSensor
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal Rücklauftemperatur"
    state_topic: "open3e/680_269_ReturnTemperatureSensor/Actual"
    unique_id: 680_269_ReturnTemperatureSensor
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal Außentemperatur"
    state_topic: "open3e/680_274_OutsideTemperatureSensor/Actual"
    unique_id: 680_274_OutsideTemperatureSensor
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal Wasserdruck"
    state_topic: "open3e/680_318_WaterPressureSensor/Actual"
    unique_id: 680_318_WaterPressureSensor
    device_class: pressure
    state_class: measurement
    icon: mdi:gauge
    unit_of_measurement: "bar"

  - name: "Vitocal Primärer Wärmetauscher Temperatur"
    state_topic: "open3e/680_320_PrimaryHeatExchangerLiquidTemperatureSensor/Actual"
    unique_id: 680_320_PrimaryHeatExchangerLiquidTemperatureSensor
    state_class: measurement
    device_class: temperature
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal Sekundärer Wärmetauscher Temperatur"
    state_topic: "open3e/680_355_SecondaryHeatExchangerLiquidTemperatureSensor/Actual"
    unique_id: 680_355_SecondaryHeatExchangerLiquidTemperatureSensor
    state_class: measurement
    device_class: temperature
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal Primärpumpe Drehzahl Prozent"
    state_topic: "open3e/680_381_CentralHeatingPump"
    unique_id: 680_381_CentralHeatingPump
    device_class: speed
    state_class: measurement
    icon: mdi:fan
    unit_of_measurement: "%"

  - name: "Vitocal Position Erweiterungsventil 1"
    state_topic: "open3e/680_389_ElectronicExpansionValveOneCurrentPositionPercent"
    unique_id: 680_389_ElectronicExpansionValveOneCurrentPositionPercent
    state_class: measurement
    icon: mdi:valve
    unit_of_measurement: "%"

  - name: "Vitocal Position Erweiterungsventil 2"
    state_topic: "open3e/680_391_ElectronicExpansionValveTwoCurrentPositionPercent"
    unique_id: 680_391_ElectronicExpansionValveTwoCurrentPositionPercent
    state_class: measurement
    icon: mdi:valve
    unit_of_measurement: "%"

  - name: "Vitocal Wartungsmeldungen"
    state_topic: "open3e/680_901_ServiceManagerIsRequired"
    unique_id: 680_901_ServiceManagerIsRequired
    icon: mdi:account-wrench

  - name: "Vitocal Störungsmeldungen"
    state_topic: "open3e/680_902_MalfunctionIdentification"
    unique_id: 680_902_MalfunctionIdentification
    icon: mdi:file-document-alert

  - name: "Vitocal Durchflusssensor"
    state_topic: "open3e/680_1043_AllengraSensor/Actual"
    unique_id: 680_1043_AllengraSensor
    state_class: measurement
    icon: mdi:gauge

  - name: "Vitocal Primäre Einlauftemperatur"
    state_topic: "open3e/680_1769_PrimaryInletTemperatureSensor/Actual"
    unique_id: 680_1769_PrimaryInletTemperatureSensor
    state_class: measurement
    device_class: temperature
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal Heizungsraum Temperatur"
    state_topic: "open3e/680_1771_EngineRoomTemperatureSensor/Actual"
    unique_id: 680_1771_EngineRoomTemperatureSensor
    state_class: measurement
    device_class: temperature
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal Primärkreislauf Lüfter 1"
    state_topic: "open3e/680_1775_PrimaryCircuitFanOne"
    unique_id: 680_1775_PrimaryCircuitFanOne
    device_class: speed
    icon: mdi:fan
    unit_of_measurement: "rps"

  - name: "Vitocal Primärkreislauf Lüfter 2"
    state_topic: "open3e/680_1776_PrimaryCircuitFanTwo"
    unique_id: 680_1776_PrimaryCircuitFanTwo
    device_class: speed
    icon: mdi:fan
    unit_of_measurement: "rps"

  - name: "Vitocal Verflüssiger Temperatur"
    state_topic: "open3e/680_2333_EconomizerLiquidTemperatureSensor/Actual"
    unique_id: 680_2333_EconomizerLiquidTemperatureSensor
    state_class: measurement
    device_class: temperature
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal Verdampfer Temperatur"
    state_topic: "open3e/680_2334_EvaporatorVaporTemperatureSensor/Actual"
    unique_id: 680_2334_EvaporatorVaporTemperatureSensor
    state_class: measurement
    device_class: temperature
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal Leistungsaufnahme Wärmepumpe"
    state_topic: "open3e/680_2488_CurrentElectricalPowerConsumptionSystem"
    unique_id: 680_2488_CurrentElectricalPowerConsumptionSystem
    device_class: power
    state_class: measurement
    icon: mdi:transmission-tower-export
    unit_of_measurement: "W"

  - name: "Vitocal Thermische Leistung"
    state_topic: "open3e/680_2496_CurrentThermalCapacitySystem"
    unique_id: 680_2496_CurrentThermalCapacitySystem
    device_class: power
    state_class: measurement
    icon: mdi:radiator
    unit_of_measurement: "W"

  - name: "Vitocal Heizwasser-Pufferspeicher Temperature"
    state_topic: "open3e/680_3016_HeatingBufferTemperatureSensor/Actual"
    unique_id: 680_3016_vitocal_HeatingBufferTemperatureSensor
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal Angeforderte Wärmeleistung Abtauen"
    state_topic: "open3e/680_2256_DesiredThermalEnergyDefrost"
    unique_id: 680_2256_DesiredThermalEnergyDefrost
    device_class: power
    state_class: measurement
    icon: mdi:transmission-tower-export
    unit_of_measurement: "W"

  - name: "Vitocal Wärmepumpe Frostschutz"
    state_topic: "open3e/6CF_2442_HeatPumpFrostProtection"
    unique_id: 6CF_2442_HeatPumpFrostProtection
    icon: mdi:electric-switch
    value_template: >
      {% if value=="0.0" %}
        {{ "Inaktiv" }}
      {% else %}
        {{ "Aktiv"}}
      {% endif %}

  - name: "Vitocal 4/3-Wege Ventil Position"
    state_topic: "open3e/680_2735_FourThreeWayValveValveCurrentPosition"
    unique_id: 680_2735_FourThreeWayValveValveCurrentPosition
    icon: mdi:valve
    value_template: >
      {{ float(value) }}

  # Vitocal 250 - Warmwasser
  - name: "Vitocal Warmwasser"
    state_topic: "open3e/680_271_DomesticHotWaterSensor/Actual"
    unique_id: 680_271_DomesticHotWaterSensor
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal Warmwasser Solltemperatur"
    state_topic: "open3e/680_396_DomesticHotWaterTemperatureSetpoint"
    unique_id: 680_396_DomesticHotWaterTemperatureSetpoint
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  # Vitocal 250 - Heizkreis 1
  - name: "Vitocal HK1 Vorlauftemperatur"
    state_topic: "open3e/680_284_MixerOneCircuitFlowTemperatureSensor/Actual"
    unique_id: 680_284_MixerOneCircuitFlowTemperatureSensor
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal HK1 Status Pumpe"
    state_topic: "open3e/680_401_MixerOneCircuitPump"
    unique_id: 680_401_MixerOneCircuitPump
    icon: mdi:pump
    value_template: >
      {% if value=="1.0" %}
        {{ "An" }}
      {% else %}
        {{ "Aus"}}
      {% endif %}

  - name: "Vitocal HK1 Position Mischventil"
    state_topic: "open3e/680_475_MixerOneCircuitThreeWayValvePositionPercent"
    unique_id: 680_475_MixerOneCircuitThreeWayValvePositionPercent
    icon: mdi:valve
    value_template: >
      {{ float(value) / 100 }}

  - name: "Vitocal HK1 Vorlauftemperatur Sollwert"
    state_topic: "open3e/680_987_MixerOneCircuitFlowTemperatureTargetSetpoint"
    unique_id: 680_987_MixerOneCircuitFlowTemperatureTargetSetpoint
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    icon: mdi:thermometer

  - name: "Vitocal HK1 Betriebsprogramm"
    state_topic: "open3e/680_1415_MixerOneCircuitOperationState/State"
    unique_id: 680_1415_MixerOneCircuitOperationState
    icon: mdi:home-variant
    value_template: >
      {% set ostate = int(value) %}
      {% if ostate==0 %}
        {{ "Abschaltbetrieb" }}
      {% elif ostate==1 %}
        {{ "Reduziert" }}
      {% elif ostate==2 %}
        {{ "Normal" }}
      {% elif ostate==3 %}
        {{ "Komfort" }}
      {% elif ostate==4 %}
        {{ "Festwert" }}
      {% elif ostate==5 %}
        {{ "Frostschutz" }}
      {% elif ostate==6 %}
        {{ "Energiesparen Reduziert" }}
      {% elif ostate==7 %}
        {{ "Energiesparen Normal" }}
      {% elif ostate==8 %}
        {{ "Energiesparen Komfort" }}
      {% else %}
        {{ value }}
      {% endif %}

  - name: "Vitocal HK1 Solltemperatur"
    state_topic: "open3e/680_1643_MixerOneCircuitCurrentTemperatureSetpoint"
    unique_id: 680_1643_MixerOneCircuitCurrentTemperatureSetpoint
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal HK1 Frostschutz"
    state_topic: "open3e/680_2855_MixerOneCircuitFrostProtectionConfiguration"
    unique_id: 680_2855_MixerOneCircuitFrostProtectionConfiguration
    icon: mdi:toggle-switch-variant
    value_template: >
      {% if value=="1.0" %}
        {{ "Aktiv" }}
      {% else %}
        {{ "Inaktiv"}}
      {% endif %}

  # Vitocal 250 - Heizkreis 2
  - name: "Vitocal HK2 Vorlauftemperatur"
    state_topic: "open3e/680_286_MixerTwoCircuitFlowTemperatureSensor/Actual"
    unique_id: 680_286_MixerTwoCircuitFlowTemperatureSensor
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal HK2 Status Pumpe"
    state_topic: "open3e/680_402_MixerTwoCircuitPump"
    unique_id: 680_402_MixerTwoCircuitPump
    icon: mdi:pump
    value_template: >
      {% if value=="1.0" %}
        {{ "An" }}
      {% else %}
        {{ "Aus"}}
      {% endif %}

  - name: "Vitocal HK2 Position Mischventil"
    state_topic: "open3e/680_476_MixerTwoCircuitThreeWayValvePositionPercent"
    unique_id: 680_476_MixerTwoCircuitThreeWayValvePositionPercent
    icon: mdi:valve
    value_template: >
      {{ float(value) / 100 }}

  - name: "Vitocal HK2 Vorlauftemperatur Sollwert"
    state_topic: "open3e/680_988_MixerTwoCircuitFlowTemperatureTargetSetpoint"
    unique_id: 680_988_MixerTwoCircuitFlowTemperatureTargetSetpoint
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal HK2 Betriebsprogramm"
    state_topic: "open3e/680_1416_MixerTwoCircuitOperationState/State"
    unique_id: 680_1416_MixerTwoCircuitOperationState
    icon: mdi:home-variant
    value_template: >
      {% set ostate = int(value) %}
      {% if ostate==0 %}
        {{ "Abschaltbetrieb" }}
      {% elif ostate==1 %}
        {{ "Reduziert" }}
      {% elif ostate==2 %}
        {{ "Normal" }}
      {% elif ostate==3 %}
        {{ "Komfort" }}
      {% elif ostate==4 %}
        {{ "Festwert" }}
      {% elif ostate==5 %}
        {{ "Frostschutz" }}
      {% elif ostate==6 %}
        {{ "Energiesparen Reduziert" }}
      {% elif ostate==7 %}
        {{ "Energiesparen Normal" }}
      {% elif ostate==8 %}
        {{ "Energiesparen Komfort" }}
      {% else %}
        {{ value }}
      {% endif %}

  - name: "Vitocal HK2 Solltemperatur"
    state_topic: "open3e/680_1644_MixerTwoCircuitCurrentTemperatureSetpoint"
    unique_id: 680_1644_MixerTwoCircuitCurrentTemperatureSetpoint
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal HK2 Frostschutz"
    state_topic: "open3e/680_2856_MixerTwoCircuitFrostProtectionConfiguration"
    unique_id: 680_2856_MixerTwoCircuitFrostProtectionConfiguration
    icon: mdi:toggle-switch-variant
    value_template: >
      {% if value=="1.0" %}
        {{ "Aktiv" }}
      {% else %}
        {{ "Inaktiv"}}
      {% endif %}

  # Vitocal 250 - Kompressor
  - name: "Vitocal Kompressor Einlauf Temperatur"
    state_topic: "open3e/680_321_CompressorInletTemperatureSensor/Actual"
    unique_id: 680_321_CompressorInletTemperatureSensor
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal Kompressor Einlauf Druck"
    state_topic: "open3e/680_322_CompressorInletPressureSensor/Actual"
    unique_id: 680_322_CompressorInletPressureSensor
    device_class: pressure
    state_class: measurement
    icon: mdi:gauge
    unit_of_measurement: "bar"

  - name: "Vitocal Kompressor Auslauf Temperatur"
    state_topic: "open3e/680_324_CompressorOutletTemperatureSensor/Actual"
    unique_id: 680_324_CompressorOutletTemperatureSensor
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal Kompressor Auslauf Druck"
    state_topic: "open3e/680_325_CompressorOutletPressureSensor/Actual"
    unique_id: 680_325_CompressorOutletPressureSensor
    device_class: pressure
    state_class: measurement
    icon: mdi:gauge
    unit_of_measurement: "bar"

  - name: "Vitocal Kompressor Öl Temperatur"
    state_topic: "open3e/680_1772_CompressorOilTemperatureSensor/Actual"
    unique_id: 680_1772_CompressorOilTemperatureSensor
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  - name: "Vitocal Kompressor Drehzahl Prozent"
    state_topic: "open3e/680_2346_CompressorSpeedPercent"
    unique_id: 680_2346_CompressorSpeedPercent
    device_class: speed
    state_class: measurement
    icon: mdi:fan
    unit_of_measurement: "%"

  - name: "Vitocal Kompressor Status"
    state_topic: "open3e/680_2351_HeatPumpCompressor"
    unique_id: 680_2351_HeatPumpCompressor
    icon: mdi:electric-switch
    value_template: >
      {% if value=="1.0" %}
        {{ "An" }}
      {% else %}
        {{ "Aus"}}
      {% endif %}

  - name: "Vitocal Kompressor Starts"
    state_topic: "open3e/680_2369_HeatPumpCompressorStatistical/starts"
    state_class: total_increasing
    unique_id: 680_2369_HeatPumpCompressorStatistical_starts
    icon: mdi:counter

  - name: "Vitocal Kompressor Betriebsstunden"
    state_topic: "open3e/680_2369_HeatPumpCompressorStatistical/hours"
    state_class: total_increasing
    unique_id: 680_2369_HeatPumpCompressorStatistical_hours
    icon: mdi:store-clock

  - name: "Vitocal Kompressor Drehzahl"
    state_topic: "open3e/680_2569_CompressorSpeedRps"
    unique_id: 680_2569_CompressorSpeedRps
    device_class: speed
    icon: mdi:fan
    unit_of_measurement: "rps"

  # Vitocal 250 - Zusatzheizung
  - name: "Vitocal Elektrische Zusatzheizung"
    state_topic: "open3e/680_2352_AdditionalElectricHeater"
    unique_id: 680_2352_AdditionalElectricHeater
    icon: mdi:electric-switch

  - name: "Vitocal Zusatzheizung Starts"
    state_topic: "open3e/680_2370_AdditionalElectricHeaterStatistical/starts"
    state_class: total_increasing
    unique_id: 680_2370_AdditionalElectricHeaterStatistical_starts
    icon: mdi:counter

  - name: "Vitocal Zusatzheizung Betriebsstunden"
    state_topic: "open3e/680_2370_AdditionalElectricHeaterStatistical/hours"
    state_class: total_increasing
    unique_id: 680_2370_AdditionalElectricHeaterStatistical_hours
    icon: mdi:store-clock

  - name: "Vitocal Leistungsaufnahme Zusatzheizung"
    state_topic: "open3e/680_2487_CurrentElectricalPowerConsumptionElectricHeater"
    unique_id: 680_2487_CurrentElectricalPowerConsumptionElectricHeater
    device_class: power
    state_class: measurement
    icon: mdi:transmission-tower-export
    unit_of_measurement: "W"
